### ISSUE TITLE
Test `nox -s dev` on CI?

### ISSUE THREAD

**Issue by arjxn-py** [pybamm-team/pybamm-cookie#21]
I tried this locally and it isn't working – `uv` doesn't seem to properly install dependencies into a `virtualenv`-created environment. I think it needs itself to create the virtual environment, i.e., using `uv venv`. I don't wish to hold the PR, so maybe we can use the original, non-`uv` solution and fix this later?

_Originally posted by @agriyakhetarpal in https://github.com/pybamm-team/pybamm-cookiecutter/pull/15#discussion_r1667023321_

**Comment by agriyakhetarpal** [comment]
Notes from the meeting: no need to test in CI, @santacodes can update this in a new PR and we can review it locally
