### ISSUE TITLE
Add versioning support for git archives

### ISSUE THREAD

**Issue by Saransh-cpp** [pybamm-team/pybamm-cookie#42]
Given that we are using `hatch-vcs` (in both the project and the template), the following two files should be added in to support versioning from VCS for a user installing the project through a git archive -

- `.git_archival.txt` ([example](https://github.com/scikit-hep/vector/blob/main/.git_archival.txt) (can be copied entirely))
- `.gitattributes` ([example](https://github.com/scikit-hep/vector/blob/main/.gitattributes) (can be copied entirely))

**Comment by santacodes** [comment]
@Saransh-cpp does that apply only for `hatch-vcs` or also for `setuptools` config?

**Comment by Saransh-cpp** [comment]
Just saw this, for all `vcs` configs, independent of the backend.
