### ISSUE TITLE
Fix CI failures and switch to official `uv` action

### ISSUE THREAD

**Issue by agriyakhetarpal** [pybamm-team/pybamm-cookie#80]
The `uv` action is failing on recent PRs because it is not able to find the `uv` executable. Astral has now adopted the action and moved it to their organisation; we should update and use it from there.

**Comment by Saransh-cpp** [comment]
@santacodes would you want to write a quick fix for this?

**Comment by agriyakhetarpal** [comment]
I see, I didn't know caching was not enabled. I think it's actually not a big problem, since the local network speeds for GHA runners are fast enough to download dependencies quickly – the benefit is in fast resolution and installation times. I would be okay to proceed without caching.
